[package]
name = "named-semaphore"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.104"
errno = "0.2.7"
thiserror = "1.0.30"

[dev-dependencies]
function_name = "0.2.0"